- name: install require packages for rbenv
  yum: name={{ item }} state=present
  with_items:
    - git
    - gcc-c++
    - glibc-headers
    - openssl-devel
    - readline
    - libyaml-devel
    - readline-devel
    - zlib
    - zlib-devel
    - libxml2
    - libxslt
    - libxml2-devel
    - libxslt-devel
    - sqlite-devel
  become: yes

- name: check installed ruby
  shell: which ruby
  register: installed_ruby
  failed_when: installed_ruby.rc not in [0, 1]

- name: download rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv
  when: installed_ruby.rc == 1

- name: download ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  when: installed_ruby.rc == 1

- name: add rbenv command to path
  lineinfile:
    dest=~/.bash_profile
    line={{ item }}
  with_items:
    - 'export PATH="$HOME/.rbenv/bin:$PATH"'
    - 'eval "$(rbenv init -)"'
  when: installed_ruby.rc == 1

- name: install ruby
  shell: /bin/bash -lc "rbenv install 2.5.1 && rbenv rehash && rbenv global 2.5.1"
  when: installed_ruby.rc == 1

- name: install bundler
  shell: /bin/bash -lc "gem install bundler"
  when: installed_ruby.rc == 1
